### PR TITLE
Enhance Attached File Display (增强附件显示)

### PR DESCRIPTION
**Pull request by kelvinelove**
### Pull Request: Enhance Attached File Display

The new feature adds a visually enhanced display for attached files, presenting the file name within a styled circular border to improve user experience and clarity.

新功能为文件附件显示添加了视觉增强效果，文件名现在以圆形边框和按钮样式呈现，以提高用户体验和可识别性。

attach

**Overview:**
This PR enhances the file attachment feature by styling the attached file name for better visibility and user experience.

**Key Changes:**
- The attached file name is now displayed with a circular border and button-like appearance.
- CSS styles include:
  - Rounded corners for a circular effect.
  - Padding for a button-like look.
  - Background color adjustments for improved contrast.

**Impact:**
This enhancement makes it clearer for users when files are attached, contributing to a more intuitive chat interface.

**Testing:**
The feature has been tested across various browsers to ensure consistent functionality and appearance.

## Summary by CodeRabbit

- **新功能**
	- 更新了附件部分的图标，改为使用 `PaperClipOutlined`。
	- 新增接口 `AttachedFile`，定义附加文件的结构，包括 `uid`、`name` 和 `size` 属性。
	- 新增状态变量 `attachedFiles`，用于管理已附加文件的数组。
	- 实现了文件选择处理功能，能够根据选择更新已附加文件的状态。
	- 附件部分现在支持文件上传，并在界面上条件性显示已附加文件的名称。
	- 在 `Sender.Header` 组件中新增了附件组件，支持拖放功能。

### CODE REVIEW

**Comment by kelvinelove** [comment]
@YumoImer  I've made the updates in the current push: 

upload

Let me know if it satisfies the guidelines.

我已经进行了更新。如果符合指南要求，请告诉我。

**Comment by YumoImer** [comment]
Thank you very much! I have reviewed the preview page, and the attachment style now conforms to the RICH specification.

Regarding the attachment upload interaction, I have recorded an example from the official website [Attachment - Combination](https://x.ant.design/components/attachments?theme=dark#attachments-demo-with-sender) which can be implemented as shown.

chrome-capture-2024-11-27 (1)

The final UI should look like this:

image

If possible, could you adjust the interaction in this PR? Thank you very much!

**Comment by YumoImer** [comment]
Thank you so much! I’ve reviewed the preview page, and it now fully aligns with the RICH design specifications! 🎉

Additionally, there are a couple of details that might need adjustment:

1. Add `overflow: scroll;` to the placeholder.
2. Add render control for `Bubble.List`:

```jsx
{!!items.length && <Bubble.List items={items} roles={roles} className={styles.messages} />}
```

**The issue caused by the first point:**
chrome-capture-2024-11-28

**The issue caused by the second point:**
image


Once these adjustments are made, I will merge this PR. 

This update means a lot to us!  **You are the first overseas contributor to X!**

Wishing you all the best, and this is a blessing from your friends in China!

**Comment by kelvinelove** [comment]
@YumoImer I've made the adjustments you suggested. I also fixed a bug I discovered that was causing an attempt to remove an attached file to add/multiply the file instead. 

attached


Thank you for appreciating me. I've been contributing to some antd projects passively (antd mobile and antd), and I am excited to also contribute to a new project.  I truly appreciate the opportunity to collaborate with such a talented team.

Warm Regards from Zimbabwe 🇿🇼

**Comment by YumoImer** [comment]
I have reviewed the PR preview page and identified some areas for improvement, which I will address through another PR.

It has been a pleasant collaboration, and thanks again! 😄

**Review by YumoImer — APPROVED** [review]
🎉

**Pull request merged**
